epochs: 20
lr: 0.005
weight_decay: 0.0005
momentum: 0.9

precision: "16-mixed"   # "32-true" / "16-mixed" / "bf16-mixed"
grad_accum_steps: 1
log_every: 20
eval_every: 1
save_every: 1

mlflow: false
mlflow_tracking_uri: ""
mlflow_experiment: "agar"
mlflow_run_name: ""

tensorboard: true
